name: Events-Demo-1
on: 
   pull_request:
     types:
       - closed
jobs:
  test-bulid-job:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github-Event
        run: echo "${{ toJSON(github.event)}}"
      - name: Downloading Code-step-1
        uses: actions/checkout@v3
      - name: Install NodeJS-step-2
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies-step-3
        run: npm ci
      - name: build project-step-4
        run: npm run build
